### ISSUE TITLE
Everything Required is Ready, yet the script failed due to invalid if arguments

### ISSUE THREAD

**Issue by Mizumo-prjkt** [ilhan-athn7/WSA_houdini_A12.1#5]
![image](https://user-images.githubusercontent.com/70519093/230217622-6cf0852c-b99e-4d58-b990-a2cfbca9f3da.png)

Debian 11.6, Waydroid 1.4.0

**Comment by Mizumo-prjkt** [comment]
forgor

![image](https://user-images.githubusercontent.com/70519093/230218035-0750c797-a914-4f14-9366-2fc672d71a35.png)

**Comment by ilhan-athn7** [comment]
Thanks for the feedback, i wrote this script poorly, it works with bash on some and works with sh on other systems.

Additionally, recent WSA uses ".vhdx" images, so i need to update script for it.

You may get houdini from [releases](https://github.com/ilhan-athn7/android_proprietary_native_bridge/releases) .
