### ISSUE TITLE
Missing binaries `linker` and `linker64` or the Android 13 pre release

### ISSUE THREAD

**Issue by ed9w2in6** [ilhan-athn7/WSA_houdini_A12.1#6]
It seems that the 2 said binaries are missing, which prevented my device from booting.

They are previously located under `/system/bin/arm/` and `/system/bin/arm64/` respectively.

**Comment by ilhan-athn7** [comment]
Hi! Android 13 is not supported.

**Comment by ed9w2in6** [comment]
@ilhan-athn7  May I ask if you can share why?  Did WSA 2211 stopped providing the required resource?

**Comment by ilhan-athn7** [comment]
![20230818_082555](https://github.com/ilhan-athn7/WSA_houdini/assets/80551220/a5be80c7-3e0b-4a63-b678-0950a8e11242)
Binaries are available and it's get loaded but Launched applications does not start, stuck at android's app splash screen.

**Comment by ed9w2in6** [comment]
Sounds like a Zygote issue to me, have you checked for errors in `logcat`?
Unfortunately I cannot debug the issue since for my case I cannot even boot.
I cannot seem to boot for Android 12.1 too, or is 12 needed instead?

**Comment by ilhan-athn7** [comment]
I did not checked deeply, HmTheBoy154 also said he can't get it to work on his own BlissOS 16 builds.

**Comment by ed9w2in6** [comment]
For the record your pre-built of 12.0.0 did work, i just didn't realised some startup service changed which didn't start the secondary Zygote.  (I use a special image)

**Comment by ilhan-athn7** [comment]
Yes, i am aware that houdini prebuilts of WSA works on BlissOS images untill Android 12 update
